### PR TITLE
Define autoload for Composer.

### PR DESCRIPTION
**Pull request by simensen**
As I mentioned [here](https://github.com/michelf/php-markdown/pull/42#issuecomment-9515517), the `composer.json` needs to have autoload information in order for Composer to actually be able to autoload the classes.

It would probably be good to have a new beta2 tag as soon as this goes in as anyone who asks for `@beta` or `minimum-stability: beta` is going to have a problem with the existing beta1 version.

It would probably be good to test an install from Packagist using `@dev` after this change is merged to make sure that there are not other issues _before_ doing the beta2 tag, though.

I'm happy to help! Excited to start directing people here over my fork. :)

### CODE REVIEW

**Comment by michelf** [comment]
Merged. Can you check that things are working fine before I add a new tag? I haven't setup anything for testing composer on my computer yet.

**Comment by simensen** [comment]
I just tested it and it looks fine. Thanks!

---

If you want a low impact isolated way to test this yourself to verify it works you can try this:

```
mkdir test-php-markdown-autoload
cd test-php-markdown-autoload
wget http://getcomposer.org/composer.phar
php composer.phar init --require=michelf/php-markdown:1.3.*@dev -n
php composer.phar install
```

Should result in:

```
Loading composer repositories with package information
Installing dependencies                                                     
  - Installing michelf/php-markdown (dev-lib 03fe190)
    Cloning 03fe1905452bbdc7e2a5a974a141434fae2a5d5a

Writing lock file
Generating autoload files
```

Then create a `test.php` file that looks like this:

``` php
<?php

require __DIR__.'/vendor/autoload.php';

use \michelf\Markdown;

$my_text = '# Hello World';

$my_html = Markdown::defaultTransform($my_text);

print $my_html;
```

Then run:

```
php test.php
```

...and you should get

``` html
<h1>Hello World</h1>
```

**Comment by michelf** [comment]
Tag added. Thanks for these detailed instructions.

**Comment by simensen** [comment]
Sure thing, glad I can help.

I tested the tag just now and it looks good. The only things I changed from the commands above was requiring `1.3.*@beta` instead of `1.3.*@dev`.

```
mkdir test-php-markdown-autoload-beta2
cd test-php-markdown-autoload-beta2
wget http://getcomposer.org/composer.phar
php composer.phar init --require=michelf/php-markdown:1.3.*@beta -n
php composer.phar install
```

Resulted in:

```
Loading composer repositories with package information
Installing dependencies
  - Installing michelf/php-markdown (1.3-beta2)
    Downloading: 100%         

Writing lock file
Generating autoload files
```

Worked like a charm.

Thanks again for working on this! I'll experiment with it a bit and start migrating some of my projects over to using php-markdown 1.3 once you start releasing stable versions. :)

**Pull request merged**
