### PR TITLE
README file added

### PR DESCRIPTION
**Pull request by theskumar**
to comply with github recomendation... 

i just renamed existing `php markdown readme.text` to `readme.md`, which was already written  with `markdown` syntax. 

This shows a nice project description on the github project page.

refer to: https://github.com/github/markup#readme

Regards
Saurabh

### CODE REVIEW

**Comment by cmillr** [comment]
@SaurabhKumar, this is a good idea.

But if you look closely, you'll notice that this pull request has become corrupted by additional commits you've made to your 'master' branch. It's not obvious at all (so don't feel bad!) but this is the way GitHub works. 

Anytime you file a pull request, you should first **_create a branch especially for your pull request**_. Then after you file the pull request, you can add more commits to the request by adding more commits to that branch.

I'd recommend closing this pull request and starting over with a new one from a topic branch, because this change really should be made.

**Comment by theskumar** [comment]
@cmillr aah... didn't know that.. this experience is totally new for me!! i'll try new to do as you said... let me try..!!

**Comment by theskumar** [comment]
@cmillr i'm little confused here if you could help me get through it... my master branch has already advanced... by 2 commits... so how do it do what you said... (i know this is going to be lot of work for a small change, but hopefully that will save this re-work next time)

Regards

**Comment by theskumar** [comment]
@cmillr did you meant in the last line i need to re-fork your repo.!!??

**Comment by cmillr** [comment]
On your working copy, you'd want to go back to the commit in question...

`git checkout e4907cc`

...create the branch...

`git checkout -b feature/markdown-readme`

...and push the branch to your github repo...

`git push <github-remote-name> feature/markdown-readme`

...then re-file the pull request using the new branch as head.

BTW, I am not the owner nor maintainer of this repo! I just noticed that your pull request was corrupted and thought I'd help you out. :)

**Comment by theskumar** [comment]
@cmillr thank you very much for the help. I'll definitely take care of this in my future pull request here or elsewhere..!! thankx

**Pull request closed without merging**
