### PR TITLE
Add MDTests and PHPUnit 5.7 to Run Them

### PR DESCRIPTION
**Pull request by michaelbutler**
For this PR, I've copied the test resources (input `.text` and their corresponding `.html`/`.xhtml` files) and added a unit test suite that can be run via PHPUnit. I've run `composer require --dev "phpunit/phpunit:5.7"` to get PHPUnit as a dev dependency. 

However at this point I'd like to ask about the tests in MDTest. Specifically, how up to date are they? Only about `50%` pass (meaning match the exact expected output). However, a lot of the failures are simply due to whitespace differences -- sometimes trailing new lines, and sometimes new line characters within the output. I guess this is what is meant by "normalized" or not. But why would it vary? Can the expectations simply be updated to match what the "true" output should be? Or does the markdown parser have options that can be tweaked to affect the output. 

Besides the whitespace differences, the remainder of the failures seem to be due to HTML encoding which I don't know why is happening. For example, given this input (`markdown/Backslash escapes.text`):

```
These should all get escaped:

Backslash: \\

Backtick: \`

Asterisk: \*

Underscore: \_
```

We expect to get `markdown/Backslash escapes.xhtml`:

```
<p>These should all get escaped:</p>

<p>Backslash: \</p>

<p>Backtick: `</p>

<p>Asterisk: *</p>

<p>Underscore: _</p>
```

What is actually produced by `Markdown::defaultTransform`:

```
<p>These should all get escaped:</p>

<p>Backslash: &#92;</p>

<p>Backtick: &#96;</p>

<p>Asterisk: &#42;</p>

<p>Underscore: &#95;</p>
```

Is it implied that the entities need to be decoded first before confirming the output is correct?

# Running the tests

The tests can be run by command line. After running `composer install` to download PHPUnit, run `vendor/bin/phpunit`.

If there's anything else you'd like to see or change, please let me know!

### CODE REVIEW

**Comment by michelf** [comment]
When I run MDTest, all the test pass fine (except for the emphasis test which behaves differently with Extra). You need to use normalization to get that result though. The normalization process will adjust whitespace, standardize the order of attributes, and resolve character entities... perhaps it does other things I forgotten about too, it's been a long time.

There are situations where we could (and probably should) be more strict and require an exact match with the expected output. There are situations where you just want a general sanity check that a change in the parser isn't breaking existing documents, normalization is great because you don't have to inspect every little detail to check if the output is correct. And I believe there are some cases where the output will have some differences between Markdown and MarkdownExtra because of internal implementation details, differences that normalization would erase allowing us to reuse the same test for both.

I guess the best course of action long term would be to be to allow each test to decide whether it should match with normalization or without. But as a starting point, I would suggest using normalization everywhere as this is how I use MDTest at the moment.

_For future reference, this is related to #256_

**Comment by michaelbutler** [comment]
Thanks a lot for the feedback! That clears up a lot. I'll add in the normalization for now and read more closely the Issue #256 .

**Comment by michaelbutler** [comment]
Ok, after adding the same (x)html normalize comparison logic to the unit tests, all 60 comparison tests pass. You can confirm by running `vendor/bin/phpunit`, and with xdebug installed code coverage:
`mkdir build && php -dmemory_limit=512M vendor/bin/phpunit --coverage-html=./build/`

It's sitting at 97.64% which is quite good. Using PHP 7.0 by the way.

**Comment by michaelbutler** [comment]
screenshot from 2018-01-27 21-01-28

**Comment by michelf** [comment]
Looks quite good. I'll give it a try.

Did you think about running the tests found in "markdown.mdtest" and "php-markdown.mdtest" against `MarkdownExtra` too? They should all pass with both `Markdown` and `MarkdownExtra`.

There's one exception to the rule above: the "Emphasis" test in "php-markdown.mdtest". Because `MarkdownExtra` treats underscore emphasis differently, that test cannot and should not pass with `MarkdownExtra`. Perhaps that test should be moved to a separate test suite ("php-markdown-regular.mdtest") so it can be tested separately only against the `Markdown` parser.

**Comment by michaelbutler** [comment]
> Did you think about running the tests found in "markdown.mdtest" and "php-markdown.mdtest" against MarkdownExtra too? They should all pass with both Markdown and MarkdownExtra.

Sounds good, will make some additional adjustments over the next 2 days.

**Comment by michaelbutler** [comment]
@michelf apologies for the delay. I've added the additional runs you recommended: `markdown.mdtest` against `MarkdownExtra`, and `php-markdown.mdtest` against `MarkdownExtra` with the exception of `Emphasis` test, which I just excluded in the data provider for that test.

**Comment by michelf** [comment]
Nice. Thank you. I'll give it a try and merge soon.

**Comment by michaelbutler** [comment]
Cool. Once merged I can start working on a second PR to enable either Travis-CI or Circle-CI integration, which will auto run unit tests on new pull requests, calculate code coverage, and etc. Do you have a preference for any service? (They're all free to use for open source projects)

**Comment by michelf** [comment]
No preference really. The CI I know is the one that comes with Xcode which I use for Mac and iOS projects. I know Travis and Circle by name, but never used them.

**Pull request merged**
