### PR TITLE
Allows footnotes to be placed elsewhere.

### PR DESCRIPTION
**Pull request by jkrrv**
I have a project where I need to be able to place the footnotes differently.  (Someone else suggested this in #286.)  I really do need it, so I figured I'd develop it and contribute the feature back. 

This change takes the existing code that generates the footnote `ol` and moves it to a separate, public function: `getFootnotes()`.  It also adds a configuration variable, `append_footnotes` which, when set to `false`, prevents the default behavior of appending the footnote list in a div at the end of the body. 

I'd be happy to adjust the nomenclature; there doesn't seem to be a precedent in the library for this sort of function.

Test results with this change in place are the same as test results without the change.

### CODE REVIEW

**Comment by michelf** [comment]
This seems like a good idea. I wonder how you're placing your footnotes though. Also, I don't think this really fits with what was requested in #286.

You probably should reset `footnotes_assembled` in `setup()` so that if you reuse the parser to parse some other text you don't get the previous run's footnotes.

Also, did you test whether `getFootnotes()` works correctly when called after the parser has done its parsing? `footnotes_ordered` gets cleaned in `teardown()`, so I'd expect the list of footnotes to always be empty once the parsing is done and `append_footnotes` is `false`.

I think instead of `append_footnotes` I'd call the configuration variable `omit_footnotes` (with `false`=included, `true`=omitted). This would better highlight the behavior relative to the default.

And perhaps we should call the function `getOmittedFootnotes()` and say it returns `nil` when `omit_footnotes` is `false` and parsing is done. This would allow us to clear the parser's variables in `teardown()` and not retain more memory than necessary, unless `omit_footnotes` is `true`. What do you think?

**Comment by jkrrv** [comment]
That all seems reasonable, and is all compatible with my use case.  I don't particularly care what the variables/functions are named, but I'd much rather change it now than have breaking changes later.  My only concern is that some of the particulars (e.g. clearing the variable in teardown if `!omit_footnotes`) aren't particularly obvious, and thus especially need appropriate attention in the documentation.  

My latest push (8bbbbf0) reflects your preferences, with one difference: with `footnotes_assembled` getting cleared in `teardown`, it has the same value as what you've requested for `getOmittedFootnotes()`.  Since it's overwritten immediately before any reads, I'm not concerned about users causing weird errors by setting that variable elsewhere. 

You asked how I'm placing my footnotes.  I'm working on a viewer for long documents (>100k words) which are divided into many relatively short chapters.  I want the user to be able to scroll past the end of a chapter and have the next chapter load via XHR.  But, I want the footnotes to appear be in a separate block on the page, with the contents of that block changing to the current chapter.  This is just easier to do if I can separate out the footnotes. 

Or, the more generic use case: sometimes you want the body and footnotes separated by something other than an `<hr />`.

**Comment by michelf** [comment]
Interesting use case.

This looks all right. I'll give it a try soon and it should be ready to merge.

**Comment by michelf** [comment]
I tested and I noticed something for which I'm not sure there's a great the solution. We're loosing the `<div>` that encloses the footnotes when looking at `footnotes_assembled` with this. I normally wouldn't mind this at all. But this means we're also loosing the `role="doc-endnotes"` attribute on that `<div>`.

I don't trust most users of the library will think of adding back the `role` attribute at the right place in their design to keep the accessibility intact. I don't think there's anything we can do in code to help that though. So I simply added some documentation to this effect in dfaa413.

For reference: #287

**Pull request merged**
