### PR TITLE
Add support for backtick fenced code blocks

### PR DESCRIPTION
**Pull request by ciarand**
Based off the work by @rbewley4 in #84, this small change adds support for backtick fenced code blocks, a la Github Flavored Markdown.

This is a grouped PR, and also includes new test cases in the mdtest fork: ciarand/mdtest@d722fdca32dc28909f4b4beafe5a22dd992aba60

### CODE REVIEW

**Comment by MightyPork** [comment]
I like this, actually I have added it into my custom markdown preprocessor already. Another good thing would be to make it possible to specify language for inline code blocks, but I am unsure about an appropriate syntax.

**Comment by ciarand** [comment]
Yeah, @MightyPork I agree, but I'm hesitant to put the effort into making those changes because I'd rather get @michelf's feedback on the initial feature first.

**Comment by michelf** [comment]
Sorry for the lack of feedback. I'm going to add backtick-fenced code blocks in the next version, but it won't come from this this pull request. There's currently three pull requests for backtick-fenced code blocks, and #132 looks like the best one.

**Comment by michelf** [comment]
Merge pull #132 instead of this one. But the feature is in HEAD now.

**Pull request closed without merging**
