### PR TITLE
Add syntax highlighting to code examples

### PR DESCRIPTION
**Pull request by NeonArray**

### CODE REVIEW

**Review by michaelbutler — APPROVED** [review]
looks good to me!

**Review by michaelbutler — CHANGES_REQUESTED** [review]
Actually sorry, since you're adding the backticks, could you remove the indenting?

e.g.

```php
$foo = 'bar';
```

**Comment by michelf** [comment]
Using the indented code block style (that can't specify which syntax to use) is done on purpose so the file is parsable by the plain `Markdown` parser. I'm not too sure I want to break that compatibility.

See previous discussion in pull request #254. Also, sorry for not chiming in earlier.

**Comment by NeonArray** [comment]
Fair enough.

**Pull request closed without merging**
