### PR TITLE
Add id and class attr for table

### PR DESCRIPTION
**Pull request by iwill**
Add id and class attr for table in Markdown:

```md
| ID | Name   | State |
| -: | :----- | :---: |
|  1 | Task A | DONE  |
|  2 | Task B | TODO  |
{ #id .class }
```

HTML:

```html
<table id="id" class="class">
   ...
</table>
```

### CODE REVIEW

**Comment by iwill** [comment]
@caiyili Can you fix the errors? 😅

**Comment by michelf** [comment]
I see in the logs:
```
Undefined offset: 4

/home/runner/work/php-markdown/php-markdown/Michelf/MarkdownExtra.php:1199
```
It seems the error comes from a notice about `$matches[4]` when there is a table with no extra attribute block. I suggest you use the null coalescing operator (`$matches[4] ?? null`) to handle more cleanly cases where the regular expression finds no extra attribute block and there is no `$matches[4]`.

**Comment by iwill** [comment]
@michelf Hi, I fixed the unit test error, would you like to merge this PR?

**Comment by michelf** [comment]
@iwill Looks good. Sorry about it taking so long. I think GitHub never notified me about you pushing more changes.

**Pull request merged**
