### PR TITLE
Allow multiple references to the same footnote

### PR DESCRIPTION
**Pull request by smokris**
Currently the following markdown doesn't parse as I'd expect:

```
    - refer to footnote A[^1]
    - refer to footnote B[^2]
    - refer to footnote A again[^1]

[^1]: footnote A
[^2]: footnote B
```

The "refer to footnote A again[^1]" line doesn't get linked to footnote A.

I've modified the footnote callback so that this is possible.

### CODE REVIEW

**Comment by michelf** [comment]
This shouldn't work like this. There is no requirement that the footnote reference markers in the Markdown source start from one, be in the right order, or be numbers at all. So you should not rely on the footnote reference marker in `$matches[1]` to be the right number. That's why there was a counter there before.

Otherwise, it's a nice patch. Can you fix that?

**Comment by michelf** [comment]
I implemented it slightly differently so that footnotes markers are properly numbered even if the user didn't use numbers as footnote reference in his Markdown file.

**Comment by taufik-nurrohman** [comment]
When writing multiple footnotes for the same reference, I got this weird reference ID pattern. Is this valid?

#### Example

``` .markdown
Lorem ipsum [^1] dolor sit amet [^2]

Lorem ipsum [^1] dolor sit amet [^2]

[^1]: Footnote 1
[^2]: Footnote 2
```

#### Footnote Output
1. Footnote 1 [↩]() [↩]()
2. Footnote 2 [↩]() [↩]()

#### Hash Produced

``` .no-highlight
#fnref:1
#fnref2:1
#fnref:2
#fnref2:2
```

Why not produce this instead?

``` .no-highlight
#fnref:1
#fnref:1-2
#fnref:2
#fnref:2-2
```

or &hellip;

``` .no-highlight
#fnref:1
#fnref-2:1
#fnref:2
#fnref-2:2
```

**Comment by michelf** [comment]
@tovic This has little to do with this four year old pull request. Please start a new issue if you want to discuss this.

**Pull request closed without merging**
