### PR TITLE
[#169] Adding hard wrap option

### PR DESCRIPTION
**Pull request by jcohlmeyer**
Adding hard wrap option to enable line breaks without two trailing spaces.

### CODE REVIEW

**Comment by michelf** [comment]
Being not sure what to do to test this, I ran `mdtest` against the parser with `hard_wrap` set to `true` and looked at the results. Obviously a lot of the tests are failing because the expected output does not match this behavior. But the interesting thing to look at is the output to determine whether it makes some sense.

For instance, it appears that this input:

```
*   Tab
    *   Tab
        *   Tab
```

produces a lot of extra `<br>` where it should not produce any. The situation is a bit similar for the handling of definition lists in MarkdownExtra. There's probably some extra newlines added for an intermediary step when parsing those lists that get converted to those extra `<br>`.

**Comment by michelf** [comment]
I just want to add that while what I wrote above might seem a bit gloomy, nested lists and definition lists are the only two instances where I could see something was wrong. With those two exceptions, this new option seems to work as intended.

**Comment by jcohlmeyer** [comment]
@michelf thanks for testing. Is there any way to easily determine the parent element from the doHardBreaks function so we can test against it to avoid these cases?

Any other ideas? I would love to help more but I am not sure where to go from here.

**Comment by michelf** [comment]
There is unfortunately no tree structure or parent element you can look at. This is all nested string processing and it's a bit ugly to work with.

We need to figure out what is the input of `doHardBreak`, figure out why it gets that input, find a way to fix the input upstream or alternatively find a way to work around the issue in `doHardBreak`.

**Comment by michelf** [comment]
Apparently I was wrong on one point when interpreting the results of parsing the test suite: definition lists work fine.

As for ordered and unordered lists, I think I have a way to fix the problem in the list parser. So I'll merge your change and push the necessary fix at the same time. It shouldn't take too long.

**Pull request merged**
